services:
  voice-match:
    extends:
      file: docker-compose.yml
      service: voice-match
    expose:
      - '7860'
    ports: []
    networks:
      - internal

networks:
  internal:
    internal: true

volumes:
  model-cache:
